// FORM FIELDS

export const FETCH_FORM_REQUEST = "FETCH_FORM_REQUEST";
export const FETCH_FORM_SUCCESS = "FETCH_FORM_SUCCESS";

// TREE FIELDS
export const FETCH_TREE_REQUEST = "FETCH_TREE_REQUEST";
export const FETCH_TREE_SUCCESS = "FETCH_TREE_SUCCESS";

// SEARCH RESOURCES

export const FETCH_RESOURCES_REQUEST = "FETCH_RESOURCES_REQUEST";
export const FETCH_RESOURCES_SUCCESS = "FETCH_RESOURCES_SUCCESS";

// CHOOSE RESOURCE CATEGORY

export const CHOOSE_CATEGORY = "CHOOSE_CATEGORY";




