# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'uk'
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: en|ru|uk
    app.notifications.email_sender: anonymous@example.com